fix: update status code return when max number of enrolled factors is exceeded
supabase/auth pull request #1676
Opened 2024-07-24 13:36 UTC by J0

## What kind of change does this PR introduce?

Return un-processable entity error instead of forbidden error.  I am guessing that is unlikely that folks depend on the status code though open to suggestions if there are concrete ways to confirm / disconfirm this.

2024-07-24 23:11 UTC, kangmingtay requested changes
let's not do this as it is considered a breaking change

2024-07-25 11:06 UTC, hf approved these changes

2024-07-25 11:06 UTC, hf commented
> let's not do this as it is considered a breaking change

It's not a breaking change, as we explicitly tell people not to rely on the status code only the status code class.

2024-07-25 14:59 UTC, closed without merging

2024-07-25 14:59 UTC, J0 commented
Closing for now as discussed