fix: possible panic if refresh token has a null session_id
supabase/auth pull request #1822
Opened 2024-10-29 11:01 UTC by kangmingtay

## What kind of change does this PR introduce?
* Prior to the `auth.sessions` table being created, some refresh tokens can contain a null `session_id`. In those cases, attempting to use those refresh tokens to obtain a new session will result in a panic. 
* This PR creates a new session for those refresh tokens that do not have a `session_id` to prevent panics from happening.

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2024-10-29 11:08 UTC, hf approved these changes
Seems harmless.

2024-10-29 12:12 UTC, cstockton requested changes
Looking at the [refresh token](https://github.com/supabase/auth/blob/master/internal/api/token_refresh.go#L85) code and [associated calls](https://github.com/supabase/auth/blob/master/internal/models/user.go#L651) I think we should take some more time to consider this change.

I think granting a new session when we can't find one is just too dangerous for the argument being made here. It's a one time inconvenience and I don't see enough code here to assert that we are hitting this specific case and the user indeed has previously authenticated.

2024-10-30 11:17 UTC, kangmingtay commented
we don't need to do the same check [here](https://github.com/supabase/auth/blob/fa020d0fc292d5c381c57ecac6666d9ff657e4c4/internal/api/token_refresh.go#L86-L101) because it's using `forUpdate = true` - the intention in this block is to retry accessing the `refresh_tokens` or `sessions` table after some time because the `FOR UPDATE` lock is being held by another transaction so it's acceptable for the session to not be found here

2024-10-30 14:28 UTC, cstockton commented
👍

2024-10-30 14:28 UTC, cstockton approved these changes

2024-10-30 14:29 UTC, merged